parent1    = Size.create(size: "サイズ")

child1_1   = parent1.children.create(size: "XSS以下")
child1_2   = parent1.children.create(size: "XS(SS)")
child1_3   = parent1.children.create(size: "S")
child1_4   = parent1.children.create(size: "M")
child1_5   = parent1.children.create(size: "L")
child1_6   = parent1.children.create(size: "XL(LL)")
child1_7   = parent1.children.create(size: "2XL(3L)")
child1_8   = parent1.children.create(size: "3XL(4L)")
child1_9   = parent1.children.create(size: "4XL(5)以上")
child1_10  = parent1.children.create(size: "FREE SIZE")


parent2    = Size.create(size: "サイズ(cm)")

child2_1   = parent2.children.create(size: "23.5cm以下")
child2_2   = parent2.children.create(size: "24cm")
child2_3   = parent2.children.create(size: "24.5cm")
child2_4   = parent2.children.create(size: "25cm")
child2_5   = parent2.children.create(size: "25.5cm")
child2_6   = parent2.children.create(size: "26cm")
child2_7   = parent2.children.create(size: "26.5cm")
child2_8   = parent2.children.create(size: "27cm")
child2_9   = parent2.children.create(size: "27.5cm")
child2_10  = parent2.children.create(size: "28cm")
child2_11  = parent2.children.create(size: "28.5cm")
child2_12  = parent2.children.create(size: "29cm")
child2_13  = parent2.children.create(size: "29.5cm")
child2_14  = parent2.children.create(size: "30cm")
child2_15  = parent2.children.create(size: "30.5cm")
child2_16  = parent2.children.create(size: "31cm以上")